<a href="https://colab.research.google.com/github/scuarlus/Matplotlib/blob/main/Parcial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Primer ejercicio: Crea un array de NumPy con los números del 1 al 100 e imprime los múltiplos
de 7.

In [ ]:
import numpy as np

array = np.arange(1, 101)
multiplos_de_7 = array[array % 7 == 0]

print("Múltiplos de 7 entre 1 y 100:", multiplos_de_7)


Múltiplos de 7 entre 1 y 100: [ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]


Segundo ejercicio Crea una matriz de 4x4 con números aleatorios enteros entre 10 y 50. Luego
reemplaza los valores impares por -1.

In [ ]:
import numpy as np


matriz = np.random.randint(10, 51, size=(4, 4))
print("Matriz original:\n", matriz)


matriz[matriz % 2 != 0] = -1
print("\nMatriz con impares reemplazados por -1:\n", matriz)


Matriz original:
 [[21 32 16 33]
 [15 47 39 47]
 [30 48 26 30]
 [20 42 15 20]]

Matriz con impares reemplazados por -1:
 [[-1 32 16 -1]
 [-1 -1 -1 -1]
 [30 48 26 30]
 [20 42 -1 20]]


Tercer ejercicio: Genera una matriz de 5x5 con valores entre 0 y 1 distribuidos uniformemente.
Luego, calcula la suma por columnas.

In [ ]:
import numpy as np


matriz = np.random.rand(5, 5)
print("Matriz 5x5:\n", matriz)


suma_columnas = matriz.sum(axis=0)
print("\nSuma por columnas:\n", suma_columnas)


Matriz 5x5:
 [[0.91029962 0.8736949  0.95205569 0.16587876 0.54636357]
 [0.64000278 0.81433224 0.72796323 0.56444902 0.58133893]
 [0.50656553 0.1330513  0.17426766 0.83499001 0.53716635]
 [0.17702115 0.90981347 0.20847979 0.51875341 0.12304037]
 [0.11996108 0.23459759 0.34823025 0.26585097 0.39200537]]

Suma por columnas:
 [2.35385017 2.9654895  2.41099662 2.34992216 2.17991458]


Cuarto ejercicio: Dado un array arr = np.array([1, 2, 3, 4, 5]), obtén su versión
invertida.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
invertido = arr[::-1]

print("Array invertido:", invertido)



Array invertido: [5 4 3 2 1]


Quinto ejercicio: Matriz identidad 6x6 multiplicada por 3

In [ ]:
identidad = np.eye(6)
resultado = identidad * 3

print("Matriz identidad * 3:\n", resultado)


Matriz identidad * 3:
 [[3. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]]


Sexto ejercicio: Array de 15 elementos entre 1 y 100 ordenado de mayor a menor

In [ ]:
array = np.random.randint(1, 101, size=15)
ordenado = np.sort(array)[::-1]

print("Array original:", array)
print("Array ordenado de mayor a menor:", ordenado)


Array original: [ 92  50  78  58  20   7  12  40  13  94 100  25  50  77  63]
Array ordenado de mayor a menor: [100  94  92  78  77  63  58  50  50  40  25  20  13  12   7]


Septimo ejercicio:  Media, mediana y desviación estándar de un array de 30 valores aleatorios entre 0 y 100
python
Copiar
Editar


In [ ]:
datos = np.random.uniform(0, 100, 30)

media = np.mean(datos)
mediana = np.median(datos)
desviacion = np.std(datos)

print("Media:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion)


Media: 48.74537752584823
Mediana: 41.686850030332884
Desviación estándar: 30.732153488655026


Octavo ejercicio: Reemplaza la fila con el menor promedio por ceros en una matriz 6x3

In [ ]:
matriz = np.random.rand(6, 3)
promedios = np.mean(matriz, axis=1)
fila_menor = np.argmin(promedios)

matriz[fila_menor] = 0

print("Matriz modificada:\n", matriz)


Matriz modificada:
 [[0.29668802 0.91006621 0.08650648]
 [0.30191327 0.31078509 0.92223613]
 [0.44001142 0.76859416 0.57715878]
 [0.         0.         0.        ]
 [0.47663631 0.75627705 0.61078409]
 [0.56039406 0.63295076 0.40709192]]


Noveno ejercicoo: Array 3x4 con np.cumsum() por filas

In [ ]:
array = np.random.randint(1, 10, size=(3, 4))
cumsum_filas = np.cumsum(array, axis=1)

print("Array original:\n", array)
print("Cumsum por filas:\n", cumsum_filas)


Array original:
 [[9 1 5 1]
 [2 3 7 2]
 [7 9 5 8]]
Cumsum por filas:
 [[ 9 10 15 16]
 [ 2  5 12 14]
 [ 7 16 21 29]]


Decimo ejercicio: Extraer los elementos de la diagonal principal
python



In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
diagonal = np.diag(arr)

print("Diagonal principal:", diagonal)


Diagonal principal: [10 50 90]


Once: Crea un DataFrame con las columnas: Nombre, Edad, Ciudad, Salario con al
menos 5 registros. Filtra los registros con salario mayor a 2.000.000.

In [ ]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Juan'],
    'Edad': [28, 35, 22, 40, 30],
    'Ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali'],
    'Salario': [2500000, 1800000, 2200000, 3000000, 1500000]
}
df = pd.DataFrame(data)
print("DataFrame original:")
print(df)

df_filtrado = df[df['Salario'] > 2000000]
print("\nSalarios mayores a 2.000.000:")
print(df_filtrado)

Doce: Importa un CSV desde una URL o archivo local y muestra las 10 primeras filas
y las 5 últimas.

In [ ]:
from google.colab import files
uploaded = files.upload()
df_csv = pd.read_csv('archivo.csv')
print("\nPrimeras 10 filas del CSV:")
print(df_csv.head(10))
print("\nÚltimas 5 filas del CSV:")
print(df_csv.tail(5))

Trece: A partir de un DataFrame con una columna de fechas, crea una nueva columna
con el nombre del mes.

In [ ]:
df_fechas = pd.DataFrame({
    'Fecha': pd.to_datetime(['2025-01-10', '2025-03-22', '2025-07-15'])
})
df_fechas['Mes'] = df_fechas['Fecha'].dt.month_name()
print("\nDataFrame con nombre del mes:")
print(df_fechas)

Catorce: Agrupa un DataFrame por la columna Ciudad y calcula el salario promedio por
ciudad.

In [ ]:
salario_promedio = df.groupby('Ciudad')['Salario'].mean()
print("\nSalario promedio por ciudad:")
print(salario_promedio)

Quince: Agrega una columna que indique si la persona es menor de 30 años (True o
False).

In [ ]:
df['Menor_de_30'] = df['Edad'] < 30
print("\nColumna 'Menor_de_30':")
print(df)


Diéciseis: Reemplaza todos los valores nulos de una columna llamada Salario por el
promedio de esa columna.

In [ ]:
df_con_nulos = df.copy()
df_con_nulos.loc[2, 'Salario'] = None  # simular un valor nulo

promedio_salario = df_con_nulos['Salario'].mean()
df_con_nulos['Salario'].fillna(promedio_salario, inplace=True)
print("\nSalario con valores nulos reemplazados por el promedio:")
print(df_con_nulos)

Diécisiete: Crea un DataFrame con columnas duplicadas y elimina las duplicadas dejando
solo una copia.

In [ ]:
df_dup = pd.DataFrame({
    'Nombre': ['Ana', 'Luis'],
    'Edad': [28, 35],
    'Nombre': ['Ana', 'Luis']  # columna duplicada simulada
})
df_sin_dup = df_dup.loc[:, ~df_dup.columns.duplicated()]
print("\nDataFrame sin columnas duplicadas:")
print(df_sin_dup)

Diéciocho: Ordena un DataFrame por dos columnas: primero por Ciudad alfabéticamente
y luego por Edad de mayor a menor.

In [ ]:
df_ordenado = df.sort_values(by=['Ciudad', 'Edad'], ascending=[True, False])
print("\nDataFrame ordenado por Ciudad (A-Z) y Edad (mayor a menor):")
print(df_ordenado)

Diécinueve: Dado el siguiente DataFrame
df = pd.DataFrame({
'Producto': ['A', 'B', 'A', 'C', 'B', 'A'],
'Precio': [1200, 1500, 1300, 1000, 1600, 1250],
'Cantidad': [3, 2, 5, 1, 2, 4]
})

Agrupa por Producto, calcula el ingreso total (Precio * Cantidad) por producto y
ordénalo de mayor a menor.

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'Producto': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Precio': [1200, 1500, 1300, 1000, 1600, 1250],
    'Cantidad': [3, 2, 5, 1, 2, 4]
    })
df['Ingreso'] = df['Precio'] * df['Cantidad']
ingresos_por_producto = df.groupby('Producto')['Ingreso'].sum()
ingresos_ordenados = ingresos_por_producto.sort_values(ascending=False)
print(ingresos_ordenados)

Veinte: Con un DataFrame de 1000 registros de ventas simuladas (puedes generarlo
con datos aleatorios que incluyan columnas como fecha, producto,
cantidad, precio_unitario, zona), responde:
● ¿Cuál es el producto más vendido por zona?
● ¿Qué día del mes se obtienen más ingresos?

In [ ]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
start_date = datetime(2023, 1, 1)
end_date = datetime(2024, 1, 1)
dates = [start_date + timedelta(days=random.randint(0, (end_date - start_date).days)) for _ in range(1000)]
productos = ['Producto ' + str(i) for i in range(1, 21)]
zonas = ['Norte', 'Sur', 'Este', 'Oeste']
data = {
    'fecha': dates,
    'producto': [random.choice(productos) for _ in range(1000)],
    'cantidad': np.random.randint(1, 11, size=1000),
    'precio_unitario': np.random.uniform(10, 200, size=1000).round(2),
    'zona': [random.choice(zonas) for _ in range(1000)]
}
df_ventas = pd.DataFrame(data)
ventas_por_zona = df_ventas.groupby(['zona', 'producto'])['cantidad'].sum().reset_index()
producto_mas_vendido_por_zona = ventas_por_zona.sort_values('cantidad', ascending=False).groupby('zona').first().reset_index()
print(producto_mas_vendido_por_zona)
df_ventas['ingreso'] = df_ventas['cantidad'] * df_ventas['precio_unitario']
ingresos_por_dia = df_ventas.groupby(df_ventas['fecha'].dt.day)['ingreso'].sum().reset_index()
dia_max_ingresos = ingresos_por_dia.sort_values('ingreso', ascending=False).head(1)

print("Día del mes con más ingresos:")
print(dia_max_ingresos)